version: 2.1
workflows:
  deploy:
    jobs:
      - install
jobs:
  install:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: development
          PGHOST: 127.0.0.1
          PGUSER: root
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - sdc-api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install && bundle clean

      # - run: sudo apt install -y postgresql-client

      # Store bundle cache
      - save_cache:
          key: sdc-api-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
